# SPDX-FileCopyrightText: © 2022 The Flvx Authors <https://github.com/kyper-io/flvx/blob/93b71a116950410b2c86dcc6efdd0031a2f79f84/AUTHORS>
#
# SPDX-License-Identifier: Apache-2.0 OR MIT

[workspace]
members = ["crates/*"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
